ENV['DEVICE'] = 'iPhone Xʀ' unless ENV.has_key?('DEVICE')
ENV['IOS_VERSION'] = '12.2' unless ENV.has_key?('IOS_VERSION')

lane :build do |options|
    scheme = options[:lib]
    analyze_scheme(scheme)
end

lane :test do |options|
    scheme = options[:lib]
    test_scheme(scheme)
end

def test_scheme(scheme)
  scan(
      workspace: '../SalesforceMobileSDK-Hybrid.xcworkspace',
      scheme: scheme,
      device: ENV['DEVICE'] + ' (' + ENV['IOS_VERSION'] + ')',
      output_directory: 'test_output',
      output_types: 'html,junit',
      code_coverage: true,
      skip_build: true
  )
end

def analyze_scheme(scheme)
    xcodebuild(
        xcargs: 'CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR=./clangReport RUN_CLANG_STATIC_ANALYZER=YES',
        workspace: '../SalesforceMobileSDK-Hybrid.xcworkspace',
        scheme: scheme,
        sdk: 'iphonesimulator',
    )
end
