# Validate changes to this class with: curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

codecov:
  branch: dev

coverage:
  precision: 2
  round: down
  range: "60...80"
  
  status:
    # Overall Libarary Requirements
    project:
      default: false  # disable the default status that measures entire project
      SalesforceHybridSDK:
        threshold: 0%
        paths: 
          - "libs/SalesforceHybridSDK/SalesforceHybridSDK/"
        flags: 
          - SalesforceHybridSDK
      SalesforceFileLogger:
        threshold: 0%
        paths: 
          - "libs/SalesforceFileLogger/SalesforceFileLogger/"
        flags: 
          - SalesforceFileLogger

    # Pull Request Requirements
    patch:
      SalesforceHybridSDK:
        target: 80%
        paths: 
          - "libs/SalesforceHybridSDK/SalesforceHybridSDK/"
        flags: 
          - SalesforceHybridSDK
      SalesforceFileLogger:
        target: 80%
        paths: 
          - "libs/SalesforceFileLogger/SalesforceFileLogger/"
        flags: 
          - SalesforceFileLogger

      
ignore:
  - "shared"
  - "hybrid"
  - "native"
  - "libs/**/*Test*/*"

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false