#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
anchors:
  - &latest-xcode    "15.2"
  - &latest-ios      "17.2"
  - &min-ios         "16.4"
  - &device          "iPhone-SE-3rd-generation"
  - &invalid         ""

executors:
  mac:
    macos:
      xcode: *latest-xcode

version: 2.1
jobs:
  run-tests:
    parameters:
      lib:
        type: string
        default: "SalesforceHybridSDK"
      xcode:
        type: string
        default: *latest-xcode
      ios:
        type: string
        default: *latest-ios
      device:
        type: string
        default: *device
      lane:
        type: string
        default: "test"
    macos:
      xcode: << parameters.xcode >>
    resource_class: macos.x86.medium.gen2
    working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      LIB: << parameters.lib >>
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v1-gem-cahce{{ checksum ".circleci/Gemfile.lock" }}
            - v1-gem-cahce
      - run: 
          name: Installing gem dependencies
          command:  |
            npm install shelljs@0.8.5
            ./install.sh
            ./build/pre-build
            cd .circleci
            sudo bundle update --bundler
            bundle check || sudo bundle install --path vendor/bundle
      - save_cache: 
          key: v1-gem-cahce{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: 
          name: Compile
          command:  |
            cd .circleci
            bundle exec fastlane build lib:<< parameters.lib >> 
      - run: 
            name: Run Tests
            command:  |
              cd .circleci
              fastlane << parameters.lane >> lib:<< parameters.lib >>
      - run: 
          name: Danger Lib
          command:  |
            danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
          background: true
          when: always
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/clangReport
          destination: Static-Analysis

#  Potential parameters that can come from the project GUI Triggers
parameters:
  xcode:
    type: string
    default: *invalid
  ios:
    type: string
    default: *invalid
  device:
    type: string
    default: *device

workflows:
  version: 2

  build-test-pr:
    when: 
      and:
        - equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          context: iOS Unit Tests
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              lane: ["PR"]
          filters:
            branches:
              only:
                - /pull.*/

  # Scheduled Trigger at ~10 PM PST Sunday/Wednesday Nights
  run-tests:
    when:
      and:
        - not: << pipeline.parameters.xcode >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >>
          context: iOS Unit Tests
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              ios: [*min-ios, *latest-ios]

  # Scheduled Trigger at ~11 PM PST Sunday/Wednesday Nights
  run-tests-beta:
    when:
      and:
        - << pipeline.parameters.xcode >>
        - << pipeline.parameters.ios >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >>
          context: iOS Unit Tests
          matrix:
            parameters:
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              device: [<< pipeline.parameters.device >>]
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]