name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 4"  # cron is UTC, this translates to 10 PM PST Wednesday.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceFileLogger, SalesforceHybridSDK]
        ios: [^26, ^18]
        include:
          - ios: ^26
            xcode: ^26
          - ios: ^18
            xcode: ^16
    uses: ./.github/workflows/reusable-test-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
    secrets: inherit

  hybrid-samples-nightly:
    strategy:
      fail-fast: false
      matrix:
        app: [AccountEditor, MobileSyncExplorerHybrid]
        ios: [^26, ^18]
        include:
          - ios: ^26
            xcode: ^26
          - ios: ^18
            xcode: ^16
    uses: ./.github/workflows/reusable-build-workflow.yaml
    with:
      app: ${{ matrix.app }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
    secrets: inherit